### PR TITLE
Upgrade the Gradle wrapper to 8.7

### PR DESCRIPTION
**Pull request by dmikurube**

### CODE REVIEW

**Review by hiroyuki-sato — COMMENTED** [review]
Does this PR relates to "Upgrade the Gradle wrapper to 8.7"?

**Comment by dmikurube** [comment]
Ah, yes, 526b783fdef14c583443e96b067cf170cf090684 is the exact commit to upgrade Gradle, and the next 4e6cf745e309c0724371de7d74169f97a0fd4485 is required to make it happen.

For some reasons, Gradle judged that this project's `compileTestJava` and `checkstyleTest` somehow used the result of `jar`, and recent Gradle requires us to declare such dependencies explicitly.

You can see the error message at: https://github.com/embulk/embulk-parser-csv/actions/runs/8829820651/job/24241673277

**Comment by hiroyuki-sato** [comment]
@dmikurube Thanks LGTM👍

**Review by hiroyuki-sato — APPROVED** [review]

**Comment by dmikurube** [comment]
Thanks!

**Pull request merged**
